language: ruby
rvm:
  - 2.3.0
cache: bundler
branches:
  only:
  - master
script:
  - git config --global user.name '${GIT_NAME}'
  - git config --global user.email '${GIT_NAME}'
  - git remote set-url origin https://${GH_TOKEN}@github.com/jeremyjousse/jeremyjousse.git
  - bundle exec middleman deploy
